# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: toor
  host:  <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: flow_base_dev

production:
  <<: *default
  database: flow_base_dev
